### 講習4 --- Numpyの基本

この次に、IRAFを使わずにFITSファイルの処理をする方法を扱いますが、その準備としてNumpyの基本を知っておきましょう。  

Numpyは、数値計算を効率よく処理するためのサードパーティモジュールです。 特に、多次元配列を取り扱う際に処理速度が速くなり、コードの表記も効率的になります。 pythonの標準の配列であるリスト型では処理が遅いため、科学計算ではNumpyの**ndarray**という多次元配列のデータ型を使います。Numpyはサードパーティモジュールですが、科学計算では標準的に使われます。このあと紹介するastropy.io.fitsおよびmatplotlibでも、このndarrayを採用しています。

次の講習で取り扱うFITSファイルの処理で最低限おさえておきたいnumpyの基本事項について説明します。


#### リスト型
まずはpythonの標準のリスト型を見てみましょう。

In [1]:
a = [1, 2, 3, 4]
b = [10, 20, 30, 40]

\+ 演算子はリストとリストの結合になります。* 演算子はリストの繰り返しを作成します。

In [2]:
a + b

[1, 2, 3, 4, 10, 20, 30, 40]

In [3]:
a * 4

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

ベクトル的に演算したい場合には、下のように、forループを回して各要素を取り出してから演算をする必要があります。


In [4]:
n = len(a)
c = [0] * n
for i in range(n):
    c[i] = a[i] + b[i]
print (c)

[11, 22, 33, 44]


#### numpyのndarray

numpyではもっとすっきりした処理、**ベクトル処理**、ができます。処理速度も速いです。

In [5]:
import numpy as np   #  一般的に np と省略される

numpy.array() 関数を使って、pythonのリストをndarray に変換します。

In [6]:
an = np.array(a)  
bn = np.array(b)

In [7]:
cn = an + bn
print (cn)

[11 22 33 44]


In [8]:
print (an * 4)

[ 4  8 12 16]


#### numpyの関数をいくつか 

numpyで用意されている関数は数多くあります。 これら関数を使ってndarrayの処理を行います。  
cellの中で、np.とタイプしてタブキーを押すと候補が表示されます。あるいはnp.mでタブキーを押すとmで始まる関数の候補が表示されます。

In [9]:
np.max(cn), np.min(cn), np.mean(cn)

(44, 11, 27.5)

**numpy.zeros( )**   

下のように、numpy.zeros( ) を使って、全要素が0の5 x 5 の二次元配列を作成することができます。

In [10]:
data = np.zeros((5, 5))
print (data)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [11]:
data[0, 1] = 2   #   [0, 1]の要素に2を代入する。

In [12]:
print (data)

[[ 0.  2.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


このdataの表示を見て気づいたかとも思いますが、 左下を原点とした二次元画像としたときに、ndarrayでは (y, x)のように xとyのindexを逆にして要素が格納されます。 print()で表示すると上下が逆さまになりますが。  
後で、astropy.io.fitsのところでも再び触れます。

**numpy.where( )**   

np.where( ) 関数は、( )内の条件を満たす要素のindexを返します。 、、ってどういうことでしょう?

まずはpythonの基本からおさらいしておきます。

In [13]:
x = np.array([-1, 2, -1, 4, 10, -2])

と、配列xがあったときに、indexを指定して

In [14]:
x[1]

2

とすればそのindexの要素を取り出すことができますね。  

np.where()を使うと、例えば次のように、要素が負のインデックスだけを取り出すことができます。

In [15]:
ix = np.where(x<0)

In [16]:
print (ix)

(array([0, 2, 5]),)


そして、そのインデックスを使って、要素を取り出すことができます。

In [17]:
x[ix]

array([-1, -1, -2])

負の値は全部一括して-9999といった負の大きな値にしておく(と目立ってあとで気付きやすい)なんてことをするときには、次のようにすればいいです。

In [18]:
x[ix] = -9999

In [19]:
x

array([-9999,     2, -9999,     4,    10, -9999])

np.where()はFITS画像処理でいろんなところで使える便利なやつです。  

初心者向けの講習できちんとやるのはちょっといきすぎかもしれませんが、こんなのがあるくらいは覚えておいてください。